#>====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====>#
#                                                                                                                      #
#    If you like this plugin           ███████╗███╗   ███╗██╗████████╗██╗  ██╗██╗   ██╗                                #
#    please donate or leave            ██╔════╝████╗ ████║██║╚══██╔══╝██║  ██║╚██╗ ██╔╝                                #
#    a review on SpigotMC!             ███████╗██╔████╔██║██║   ██║   ███████║ ╚████╔╝                                 #
#                                      ╚════██║██║╚██╔╝██║██║   ██║   ██╔══██║  ╚██╔╝                                  #
#    Any amount helps! Thanks :)       ███████║██║ ╚═╝ ██║██║   ██║   ██║  ██║   ██║                                   #
#    PayPal: fortyeffsmc@gmail.com     ╚══════╝╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝  ╚═╝   ╚═╝                                   #
#                                                                                                                      #
#>====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====> >====>#
Version: 1.0.0 # Do not change this

General:
  RightClickGUI: true # Whether right clicking opens smithy menu. Disable this if using McMMO.

Currency:
  Name: Energy:Energy      # Give the singular and plural form separated by a colon if you change this
  StartingBalance: 100     # This is the currency accumulated on the tool by using it
  DecimalPlaces: 0         # How many decimal places to show to currency total
  GainRate: 3.0            # How much currency to gain per block broken

Tools: #This section is for setting up your tools. You can add or remove any of these tool sections with any name you wish.
  Tool1:
    DisplayName: '&6Smithy Powerdrill' # Set to '' to keep the item's normal name. Item's can be renamed at any time without breaking the tool
    Item: Diamond_Pickaxe
    RepairCost: 1000
    CurrencyGain: 0.1      # This defines how much currency a player gets per block broken.
    DefaultEnchants: DIG_SPEED:1:20,DURABILITY:1:2:3:4:5:6:7:8:9:10
    # Enchants follow this format EnchantName:StartingLevel:MaxLevel - Separate enchants with a comma
    # Full list of enchant names https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
    Costs:
      UpgradeInitial: 100,150  # Include a upgrade starting cost for each enchant above, separated by a comma
      Multiplier: 1.5,1.6           # Each additional level multiplier. For example 100 starting cost and 1.5 multiplier would be 100, 150, 225 etc.
    UnlockableEnchants: LOOT_BONUS_BLOCKS:1:5,SILK_TOUCH:1:5,DAMAGE_ALL:1:2:3:4:5,ARROW_FIRE:1:2:3:4
    UnlockCosts:
      UnlockCost: 1000,10000
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6
  Tool2:
    DisplayName: 'Smithy Treefeller'
    Item: Diamond_Axe
    CurrencyGain: 0.1
    RepairCost: 1000
    DefaultEnchants: DIG_SPEED:1:20,DURABILITY:1:10
    Costs:
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6
    UnlockableEnchants: LOOT_BONUS_BLOCKS:1:2:3,SILK_TOUCH:1:2:3
    UnlockCosts:
      UpgradeInitial: 1000,10000
      UpgradeStartingCost: 100,150
      Multiplier: 1.5,1.6
  Tool3:
    DisplayName: 'Smithy Excavator'
    Item: Diamond_Shovel
    CurrencyGain: 0.1
    RepairCost: 1000
    DefaultEnchants: DIG_SPEED:1:20,DURABILITY:1:10
    Costs:
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6
    UnlockableEnchants: LOOT_BONUS_BLOCKS,SILK_TOUCH
    UnlockCosts:
      UnlockCost: 1000,10000
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6
  Tool4:
    DisplayName: 'Smithy Powertiller'
    Item: Diamond_Hoe
    CurrencyGain: 0.1
    RepairCost: 1000
    DefaultEnchants: DIG_SPEED:1:20,DURABILITY:1:10
    Costs:
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6
    UnlockableEnchants: LOOT_BONUS_BLOCKS,SILK_TOUCH
    UnlockCosts:
      UnlockCost: 1000,10000
      UpgradeInitial: 100,150
      Multiplier: 1.5,1.6

GUI:
  GUIName: 'Tool Upgrade Menu'
  BackButton:
    Item: 'STONE'
    ItemName: 'Previous Menu'
    InventorySlot: 47
  PreviousPageButton:
    Item: 'ARROW'
    ItemName: 'Previous Page'
    InventorySlot: 48
  NextPageButton:
    Item: 'ARROW'
    ItemName: 'Next Page'
    InventorySlot: 50
  CloseButton:
    Item: 'BARRIER'
    ItemName: 'Close Menu'
    InventorySlot: 49
  MenuItems:
    Tool:
      MenuName: 'Tool Stats'
      ItemName: 'Tool Stats'
      Lore: '&eThis tool upgrade menu lets you level up your item|&eand increase its power and usefulness!' # Separate lore into new lines with the pipe symbol (|).
      InventorySlot: 4
    Enchants:
      MenuName: 'Smithy Enchant Upgrades'
      Item: DIAMOND_PICKAXE
      ItemName: 'Enchants'
      Lore: '&eUse your points to buy|&ebetter enchants for your tools!' # Separate lore into new lines with the pipe symbol (|).
      InventorySlot: 11
    Repair:
      MenuName: 'Smithy Repair'
      Item: ANVIL
      ItemName: 'Repair'
      Lore: '&eUse your points to repair|&ea tool!' # Separate lore into new lines with the pipe symbol (|).
      InventorySlot: 12
    Particles:
      MenuName: 'Smithy Particle Upgrades'
      Item: BLAZE_POWDER
      ItemName: 'Particles'
      Lore: '&eUnlock particles for your tool' # Separate lore into new lines with the pipe symbol (|).
      InventorySlot: 13
    Conjure:
      MenuName: 'Smithy Conjuring'
      Item: GOLDEN_APPLE
      ItemName: 'Conjuring'
      Lore: '&eConjure powerful items using the|&eenergy from your tool' # Separate lore into new lines with the pipe symbol (|).
      InventorySlot: 14